# Generated by Django 4.1.3 on 2024-12-19 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedentPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Antecedent', models.TextField()),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentpatient', to='patients.patient')),
            ],
        ),
    ]
