# Generated by Django 4.1.3 on 2024-12-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_antecedentpatient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antecedentpatient',
            old_name='date',
            new_name='Date',
        ),
    ]
