# Generated by Django 5.1.4 on 2024-12-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_rename_date_antecedentpatient_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
