# Generated by Django 4.1.3 on 2025-01-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='NSS',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
