# Generated by Django 4.1.3 on 2024-12-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('Medecin_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('Specialite', models.CharField(choices=[('CARD', 'Cardiologie'), ('PED', 'Pédiatrie'), ('ORTH', 'Orthopédie'), ('DERM', 'Dermatologie'), ('GEN', 'Médecin généraliste')], default='GEN', max_length=5)),
                ('Telephone', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('MotDePasse', models.CharField(max_length=100)),
                ('patients', models.ManyToManyField(related_name='medecins', to='patients.patient')),
            ],
        ),
    ]
