# Generated by Django 4.1.3 on 2024-12-18 21:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('medecins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('Consultation_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Motif', models.TextField()),
                ('Datecons', models.DateField(default=django.utils.timezone.now)),
                ('Diagnostic', models.TextField()),
                ('Medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='medecins.medecin')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient')),
            ],
        ),
    ]
