# Generated by Django 4.1.3 on 2024-12-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0002_alter_medecin_email_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='Datecons',
            field=models.DateField(auto_now=True),
        ),
    ]
