# Generated by Django 4.1.3 on 2024-12-19 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0003_alter_consultation_datecons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecert', models.DateField(auto_now=True)),
                ('description', models.TextField()),
                ('Consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to='medecins.consultation')),
            ],
        ),
    ]
