# Generated by Django 4.1.3 on 2024-12-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0004_certificat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificat',
            name='datecert',
            field=models.DateField(),
        ),
    ]
