# Generated by Django 4.1.3 on 2024-12-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0005_alter_certificat_datecert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificat',
            old_name='datecert',
            new_name='Datecert',
        ),
        migrations.RenameField(
            model_name='certificat',
            old_name='description',
            new_name='Description',
        ),
    ]
