# Generated by Django 4.1.3 on 2024-12-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0007_alter_certificat_datecert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.TextField()),
                ('Dosage', models.TextField()),
                ('Fabricant', models.TextField()),
                ('Forme', models.CharField(choices=[('comprimé', 'Comprimé'), ('sirop', 'Sirop'), ('capsule', 'Capsule'), ('pommade', 'Pommade'), ('autre', 'Autre')], default='autre', max_length=100)),
            ],
        ),
    ]
