# Generated by Django 4.1.3 on 2024-12-19 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0008_medicament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('Consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='medecins.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='OrdonnanceMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Posologie', models.CharField(max_length=200)),
                ('Medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance_medicaments', to='medecins.medicament')),
                ('Ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance_medicaments', to='medecins.ordonnance')),
            ],
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='Medicaments',
            field=models.ManyToManyField(related_name='ordonnances', through='medecins.OrdonnanceMedicament', to='medecins.medicament'),
        ),
    ]
