# Generated by Django 4.1.3 on 2024-12-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0009_ordonnance_ordonnancemedicament_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infirmier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.TextField()),
                ('Prenom', models.TextField()),
                ('Telephone', models.TextField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
