# Generated by Django 4.1.3 on 2024-12-19 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('medecins', '0010_infirmier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soininfirmier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True)),
                ('Description', models.TextField()),
                ('Infirmier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soininfirmier', to='medecins.infirmier')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soininfirmier', to='patients.patient')),
            ],
        ),
    ]
