# Generated by Django 4.1.3 on 2024-12-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0012_laborantin'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborantin',
            name='Prenom',
            field=models.TextField(default='lal'),
            preserve_default=False,
        ),
    ]
