# Generated by Django 4.1.3 on 2024-12-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0014_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
