# Generated by Django 4.1.3 on 2024-12-19 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_rename_date_antecedentpatient_date'),
        ('medecins', '0015_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rapport', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('Laborantin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilan', to='medecins.laborantin')),
                ('Medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilan', to='medecins.medecin')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilan', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.TextField()),
                ('Image', models.TextField()),
                ('Bilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='medecins.bilan')),
            ],
        ),
    ]
