# Generated by Django 4.1.3 on 2024-12-19 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0016_bilan_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bilan',
            old_name='date',
            new_name='Date',
        ),
    ]
