# Generated by Django 4.1.3 on 2025-01-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0019_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='PatientSymptoms',
            field=models.TextField(default='No symptoms reported'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='diagnosticEstablished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='measure',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='measureValue',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='consultation',
            name='nextcons',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patientHistory',
            field=models.TextField(default='No previous history'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='Diagnostic',
            field=models.TextField(default='Pending'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='Motif',
            field=models.TextField(default='General consultation'),
        ),
    ]
