# Generated by Django 4.1.3 on 2025-01-04 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0020_consultation_patientsymptoms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='Diagnostic',
            new_name='diagnostic',
        ),
        migrations.RenameField(
            model_name='consultation',
            old_name='nextcons',
            new_name='nextConsultation',
        ),
    ]
