# Generated by Django 4.1.3 on 2025-01-04 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_nss'),
        ('medecins', '0021_rename_diagnostic_consultation_diagnostic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilan',
            name='Image',
            field=models.URLField(blank=True, default='https://via.placeholder.com/150', null=True),
        ),
        migrations.AddField(
            model_name='bilan',
            name='Informations',
            field=models.TextField(default='No additional information provided.'),
        ),
        migrations.AddField(
            model_name='bilan',
            name='Type',
            field=models.TextField(default='General'),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='Laborantin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laborantin_bilan', to='medecins.laborantin'),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='Medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilans', to='medecins.medecin'),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='Patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilans', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='Rapport',
            field=models.TextField(default='No report provided.'),
        ),
    ]
