# Generated by Django 4.1.3 on 2025-01-04 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_nss'),
        ('medecins', '0022_bilan_image_bilan_informations_bilan_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilan',
            name='Image',
        ),
        migrations.AddField(
            model_name='bilan',
            name='RadiologistName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='Informations',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='Laborantin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bilan_laborantin', to='medecins.laborantin'),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='Medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilan', to='medecins.medecin'),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='Patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilan', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='Rapport',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='Type',
            field=models.TextField(),
        ),
    ]
