# Generated by Django 4.1.3 on 2025-01-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0023_remove_bilan_image_bilan_radiologistname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilan',
            name='Rapport',
            field=models.TextField(blank=True, null=True),
        ),
    ]
