# Generated by Django 4.1.3 on 2025-01-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0025_ordonnance_date_ordonnance_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radiologistID', models.IntegerField()),
                ('patientID', models.IntegerField()),
                ('image', models.ImageField(upload_to='radio_reports/')),
                ('description', models.TextField(max_length=1200)),
                ('date_signed', models.DateField()),
                ('signature_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
