# Generated by Django 4.1.3 on 2025-01-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0026_radioreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labID', models.IntegerField()),
                ('patientID', models.IntegerField()),
                ('generate_graph', models.BooleanField(default=False)),
                ('blood_pressure', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_sugar', models.CharField(blank=True, max_length=50, null=True)),
                ('cholesterol', models.FloatField(blank=True, null=True)),
                ('Na', models.FloatField(blank=True, null=True)),
                ('hemoglobine', models.FloatField(blank=True, null=True)),
                ('iron', models.FloatField(blank=True, null=True)),
                ('date_signed', models.DateField()),
            ],
        ),
    ]
