# Generated by Django 4.1.3 on 2025-01-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0027_labreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.TextField()),
                ('Prenom', models.TextField()),
                ('Telephone', models.TextField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
