# Generated by Django 4.1.3 on 2025-01-30 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0026_alter_ordonnance_date'),
        ('medecins', '0029_remove_soininfirmier_infirmier_and_more'),
    ]

    operations = [
    ]
